name = "portfolio"

# change account_id to your own
[[kv_namespaces]]
binding = "COMMENTS"
id = "a8b96ad55a6b4bcf9329ad26c294e181"

# Change the database name and id to your own
[[d1_databases]]
binding = "DB"
database_name = "portfolio"
database_id = "6d4dbbba-aa9d-43bd-b982-5ab3447283b2"
preview_database_id = "DB"
